site_name: robomq.io
site_url: rabomq.io/docs
site_description: User documentation and SDK for robomq.io
site_favicon: favicon.ico
#docs_dir: <path to your local folder on local git where docs are>
#site_dir: < path where mkdocs will generate HTML. keep it outside of the git directory>
pages:
- ['index.md', '', 'What is Robomq.io']
#- ['user-guide/setup.md', '', 'Initial Setup Using Robomq.io']
- ['user-guide/gettingStarted.md', '', 'Getting Started']
- ['user-guide/creatingNewApplication.md', '', 'Creating a New Application']
#- ['user-guide/installation.md', '', 'Installation for Development']
- ['user-guide/m2m/deviceIntegration.md', '', 'IoT and M2M Integration']
- ['user-guide/applicationIntegration.md', '', 'Application Integration']
- ['user-guide/one-one/one-one.md', 'User Guide', 'One to One (Direct) Messaging']
- ['user-guide/broadcast/broadcast.md', 'User Guide', 'Broadcast (Publish/Subscribe)']
- ['user-guide/routing-key/routing-key.md', 'User Guide', 'Key based Message routing']
- ['user-guide/topic/topic.md', 'User Guide', 'Filter based Message routing']
- ['user-guide/request-reply/request-reply.md', 'User Guide', 'Request - Reply']
- ['user-guide/mqtt/MQTT.md', 'User Guide', 'MQTT']
- ['user-guide/stomp/STOMP.md', 'User Guide', 'STOMP']

#- ['user-guide/m2m/arduino.md', 'User Guide', ' Audrino']
#- ['user-guide/m2m/raspberry.md', 'User Guide', 'Raspberry Pi ']
- ['about/about.md', '', 'About']
theme: readthedocs
#theme: cerulean
#heme: bootstrap

