site_name: robomq.io
site_url: rabomq.io/docs
site_description: User documentation and SDK for robomq.io
site_favicon: favicon.ico
repo_url: https://github.com/robomq/robomq.io/
docs_dir: docs
#site_dir: < path where mkdocs will generate HTML. keep it outside of the git directory>
pages:
- ['index.md', '', 'What is Robomq.io']
- ['user-guide/gettingStarted.md', '', 'Getting Started']
- ['user-guide/creatingNewApplication.md', '', 'Creating a New Application']
- ['user-guide/deviceIntegration.md', '', 'IoT and M2M Integration']
- ['user-guide/applicationIntegration.md', '', 'Application Integration']
- ['user-guide/one-one.md', 'User Guide', 'One to One (Direct) Messaging']
- ['user-guide/broadcast.md', 'User Guide', 'Broadcast (Publish/Subscribe)']
- ['user-guide/routing-key.md', 'User Guide', 'Key based Message routing']
- ['user-guide/topic.md', 'User Guide', 'Filter based Message routing']
- ['user-guide/request-reply.md', 'User Guide', 'Request - Reply']
- ['user-guide/MQTT.md', 'User Guide', 'MQTT']
- ['user-guide/STOMP.md', 'User Guide', 'STOMP']
- ['about/about.md', '', 'About']
theme: readthedocs


