site_name: robomq.io
site_url: rabomq.io/docs
site_description: User documentation and SDK for robomq.io
site_favicon: favicon.ico
repo_url: https://github.com/robomq/robomq.io/
docs_dir: docs
pages:
- ['index.md', '', 'What is Robomq.io']
- ['gettingStarted.md', '', 'Getting Started']
- ['creatingNewApplication.md', '', 'Creating a New Application']
- ['deviceIntegration.md', '', 'IoT and M2M Integration']
- ['applicationIntegration.md', '', 'Application Integration']
- ['SDK.md', '', 'SDK & example codes']
- ['AMQP.md', 'User Guide', 'AMQP Introduction']
- ['one-one.md', 'User Guide', 'One to One (Direct) Messaging']
- ['broadcast.md', 'User Guide', 'Broadcast (Publish/Subscribe)']
- ['routing-key.md', 'User Guide', 'Key based Message routing']
- ['topic.md', 'User Guide', 'Filter based routing (Topic)']
- ['request-reply.md', 'User Guide', 'Request and Reply']
- ['MQTT.md', 'User Guide', 'MQTT']
- ['STOMP.md', 'User Guide', 'STOMP']
- ['WebSTOMP.md', 'User Guide', 'WebSTOMP']
- ['about.md', '', 'About']
theme: readthedocs